### ISSUE TITLE
Support for custom Java versions

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/setup-scala#19]
Jabba supports a custom version syntax which installs from a specific source, regardless of name. In this syntax, the `=` character is part of the "name" of the JDK, where the right side is a URI indicating from where it should be downloaded.

However, this action doesn't pass things off directly to `jabba`, and instead first uses `ls-remote` and `grep` to sanity-check the name. This prevents the use of custom names, which closes the door to one of the two workarounds for the current GraalVM situation.

A relatively simple fix here would be to look for the `=` character and bypass `ls-remote` if it is found, since presumably then the user knows what they're doing.

**Comment by olafurpg** [comment]
Thank you for reporting! I think this is a good idea 👍 

I have so far worked around this issue by installing the custom JDK after setup-scala like here https://github.com/scalameta/scalafmt/blob/31abcfcbe817bde76160c579dcf9dcd316547f8a/.github/workflows/ci.yml#L44-L53

```yml
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        include:
          - os: macOS-latest
            url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-darwin-amd64-20.0.0.tar.gz
            artifact: scalafmt-macos
          - os: ubuntu-latest
            url: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.0.0/graalvm-ce-java11-linux-amd64-20.0.0.tar.gz
            artifact: scalafmt-linux
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
      - run: jabba install graal-custom@20.0=tgz+${{ matrix.url }}
```

This workaround isn't ideal since you first install the default JDK that you don't use.
