### ISSUE TITLE
Speeding up - sbt version and sbt download

### ISSUE THREAD

**Issue by Zejnilovic** [olafurpg/setup-scala#33]
I have noticed that when the action runs, it starts downloading the sbt version specified in project and it takes almost a minute to download. Coupled with cross-compilation and CI running for all commits in a PR, it seems like a lot.

Is there a way to specify sbt version for the setup. Let's say:
```
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
          sbt-version: "1.4.5"
```
