### ISSUE TITLE
Caching for sbt and project dependencies

### ISSUE THREAD

**Issue by plokhotnyuk** [olafurpg/setup-scala#5]
I've tried the following configuration on a relatively small repo with less than 100 dependencies and found that it saves ~5 seconds:
```
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.properties') }}
```
Would it be possible to have caching for project dependencies and sbt itself turned on by default?
