### ISSUE TITLE
scalac

### ISSUE THREAD

**Issue by hanm2019** [olafurpg/setup-scala#52]
how can I use `scalac` command?

**Comment by berndschatz** [comment]
As far as i understand there is no scala installed, so the name is a little bit missleading !?

**Comment by laughedelic** [comment]
I think this action doesn't intend to install Scala compiler. It's rarely needed on its own.
You could use https://github.com/coursier/setup-action instead:

```yaml
    - uses: coursier/setup-action@v1
      with:
        apps: scalac
```

If you want to run single-file scripts, consider using [Ammonite](https://ammonite.io/) (`amm`) or [Scala CLI](https://scala-cli.virtuslab.org/) (`scala-cli`) instead of calling the compiler directly. You can also install them with cousier/setup-action.
